### PR TITLE
Common Categories

### LINKED ISSUE #147: Common categories not working
Common categories in the right panel and header menu are not working.

image

They should be listed from most popular to least popular. With different stylying to 3 top ones, and then another one for 3 next ones, followed by grey color for less popular ones.
Clicking them should redirect to articles listing of said category.
While moving a mouse over them, user should see pointer cursor.

### PR DESCRIPTION
**Pull request by Jordan141**
Common categories logic, currently fine because I don't expect us to have a lot of users but should we start hitting < 1k it would improve performance to cache this result or do it less often.

Algorithm and functionality done. Just styling left.

Fixes #147

### CODE REVIEW

File: app/routes/index.js [hunk 1]
```diff
@@ -34,7 +34,9 @@ router.get('/', async (req, res) => {
     try {
         const latestArticles = await Article.find(query).sort('-createdAt').exec()
         const topStories = await findTopStories()
-        return res.render('index', {title: 'Pinch of Code', articles: latestArticles, topStories, currentUser: req.user, page: 'articles', isReviewing: false, currentCategory})
+        const commonCategories = await findCommonCategories()
+        console.log(commonCategories)
```
Comment (michaelKurowski) [inline app/routes/index.js:38]: Logging

**Comment by michaelKurowski** [comment]
I'll do styling and merge them

**Review by michaelKurowski — APPROVED** [review]
