### PR TITLE
Extract image functionality to utils

### LINKED ISSUE #112: Uploading image header
Uploading article's header image causes error
```
(node:19) UnhandledPromiseRejectionWarning: Error: /usr/src/app/content/articles/images/5fe11f737f25360013e40eb6.jpeg: unable to open for write

```

### PR DESCRIPTION
**Pull request by Jordan141**
Resolves #112 

This will extract image and IO workings to utils class with extra error checking and handling.

### CODE REVIEW

**Comment by Jordan141** [comment]
Bug: Invalid permissions error is thrown but the code continues anyway

**Comment by Jordan141** [comment]
ready for review

File: app/routes/articles.js [hunk 1]
```diff
@@ -35,23 +32,15 @@ router.post('/', isLoggedIn, hasAuthorRole, (req, res) => {
     
     Article.create({author, title, description, body}, (err, article) => {
         if(err) throw err
-        const filePath = path.join(__dirname + '../../content', 'articles', 'images', String(article._doc._id) + '.jpeg')
-        sharp(header.data).toFormat(JPEG).jpeg(JPEG_OPTIONS).toFile(filePath).then(() => {
+        const imageName = String(article._doc._id) + '.jpeg'
+        setArticleHeaderImage(header, imageName)
+        .then(() => {
```
Comment (michaelKurowski) [inline app/routes/articles.js:37]: intendation

File: app/routes/articles.js [hunk 2]
```diff
@@ -118,22 +107,30 @@ router.post('/listings', listingsLimit, (req, res) => {
...
 })
 
-router.get('/images/:id', async (req, res) => {
-    if(!req?.params?.id || !req?.user?.username) res.sendStatus(404)
-    const dirPath = path.join(__dirname + '../../content', 'articles', 'images')
-    if(!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, {recursive: true})
+//GET Article Images
+router.get('/image/:id', async (req, res) => {
+    if(!req?.params?.id) return res.sendStatus(404)
+    const width = req.query?.width ?? null
```
Comment (michaelKurowski) [inline app/routes/articles.js:113]: Isn't `req.query?.width` enough

Comment (michaelKurowski) [reply app/routes/articles.js:113]: Since null suggests that the variable is defined, as null.
Here it's just undefined.

File: app/routes/articles.js [hunk 3]
```diff
@@ -118,22 +107,30 @@ router.post('/listings', listingsLimit, (req, res) => {
...
+})
 
+//POST Upload Article Content Images
+router.post('/images', isLoggedIn, async (req, res) => {
     try {
-        const file = await fs.promises.readFile(path.join(dirPath, req.params.id))
-        if(!file) return res.sendStatus(404)
-        return res.send(file)
+        if(req?.user?.role !== 'author') return res.render('error', {code: 400, msg: 'You are not authorized to do this'})
+        const image = req.files?.image ?? null
```
Comment (michaelKurowski) [inline app/routes/articles.js:123]: undefined?

File: app/routes/index.js [hunk 4]
```diff
@@ -230,32 +199,15 @@ router.get('/captcha', (req, res) => {
 })
 
 //Get profile picture
-router.get('/image/:username', async (req, res) => {
+router.get('/image/:username', (req, res) => {
     const username = req.params?.username ?? null
-    const width = parseInt(req.query?.width ?? DEFAULT_IMAGE_WIDTH)
-    const height = parseInt(req.query?.height ?? DEFAULT_IMAGE_HEIGHT)
+    const width = req.query?.width ?? null
```
Comment (michaelKurowski) [inline app/routes/index.js:204]: undefined?

File: app/routes/articles.js (hunk 2 above)
Comment (michaelKurowski) [reply app/routes/articles.js:113]: Actually I believe that there will always be `req.query` so you can just do `const {width, height} = req.query`

**Review by michaelKurowski — APPROVED** [review]
