### PR TITLE
Bugfix - Image Naming

### LINKED ISSUE #221: Image naming bug
After changing your full name or article title, you'll start looking for the wrong image.

Solution: Create junk name and add related image's names to schema

### PR DESCRIPTION
**Pull request by Jordan141**
fixes #221

- Article header
- User profile

Bug in question:
User sets their profile picture under name A
User changes their name to name B
Profile picture was saved under name A, thus user can no longer find it as they now have name B

### CODE REVIEW

File: app/routes/articles.js [hunk 1]
```diff
@@ -133,12 +132,12 @@ router.post('/listings', listingsLimit, (req, res) => {
...
 
-//GET Article Images
+
 router.get('/image/:link', async (req, res) => {
     if(!req.params.link) return res.sendStatus(404)
     const {width, height} = req.query
-    if(width && height) return getArticleImage(res, req.params.link, width, height).catch(err => req.log(err))
-    return getArticleImage(res, req.params.link).catch(err => req.log(err))
+    const article = await Article.findOne({link: req.params.link}).exec()
+    return getArticleImage(res, article?.headerUrl || req.params.link, width, height)
```
Comment (Jordan141) [inline app/routes/articles.js:140]: If the link provided is not the title of an article, it's either a content image or it doesn't exist. Hence why I'm still propagating req.params.link

**Review by michaelKurowski — APPROVED** [review]
